# Generated by Django 5.1.15 on 2026-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Raw shipment-confirmation text, as received.')),
                ('parsed', models.JSONField(help_text='Model auto-parse: a list of ShipmentLine dicts.')),
                ('corrected', models.JSONField(blank=True, help_text="Reviewer's corrected parse (list of ShipmentLine dicts); blank if the auto-parse was fine.", null=True)),
                ('reviewed', models.DateTimeField(blank=True, help_text='When a reviewer signed off. Blank means still in the review queue.', null=True)),
                ('exclude', models.BooleanField(default=False, help_text='drop from training')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
